# Generated by Django 5.2.8 on 2025-11-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhooklog',
            name='remarks',
            field=models.TextField(default=''),
        ),
    ]
