# Generated by Django 5.2.8 on 2025-11-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_webhooklog_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('no_payment_required', 'No Payment Required'), ('canceled', 'Canceled'), ('processing', 'Processing'), ('requires_payment_method', 'Requires Payment Method'), ('requires_confirmation', 'Requires Confirmation'), ('requires_action', 'Requires Action'), ('requires_capture', 'Requires Capture'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='unpaid', max_length=100),
        ),
    ]
