# Generated by Django 5.2.8 on 2025-11-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('no_payment_required', 'No Payment Required'), ('processing', 'Processing'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='unpaid', max_length=100),
        ),
    ]
