# Generated by Django 5.2.8 on 2025-12-01 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_historicalpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpayment',
            name='type',
            field=models.CharField(choices=[('INSTAGRAM_USER_STORY_CREDIT', 'Instagram User Story Credit'), ('INSTAGRAM_USER_PROFILE_CREDIT', 'Instagram User Profile Credit')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('INSTAGRAM_USER_STORY_CREDIT', 'Instagram User Story Credit'), ('INSTAGRAM_USER_PROFILE_CREDIT', 'Instagram User Profile Credit')], max_length=255, null=True),
        ),
    ]
