# Generated by Django 5.2.8 on 2025-12-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_gatewayoption_historicalgatewayoption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpaymentsetting',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='paymentsetting',
            name='gateway',
        ),
    ]
