coverage:
  status:
    project:
      default:
        target: 80%          # Target coverage percentage
        threshold: 2%        # Allow 2% drop before failing
    patch:
      default:
        target: 80%          # New code should have 80% coverage
        threshold: 2%

  precision: 2
  round: down
  range: "70...100"

ignore:
  - "*/migrations/*"
  - "*/tests/*"
  - "manage.py"
  - "merge_production_dotenvs_in_dotenv.py"
  - "config/wsgi.py"
  - "config/asgi.py"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
