# Generated by Django 5.2.8 on 2025-11-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_firebaseadminsetting_service_account_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', help_text='Stripe API Key', max_length=255)),
                ('webhook_secret', models.CharField(blank=True, default='', help_text='Stripe Webhook Secret', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stripe Setting',
            },
        ),
    ]
