# Generated by Django 5.2.8 on 2025-12-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0009_stripesetting"),
    ]

    operations = [
        migrations.AddField(
            model_name="stripesetting",
            name="cancel_url",
            field=models.URLField(
                blank=True,
                default="https://instarchiver.com/cancel",
                help_text="URL to redirect to after cancelled payment",
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name="stripesetting",
            name="success_url",
            field=models.URLField(
                blank=True,
                default="https://instarchiver.com/success",
                help_text="URL to redirect to after successful payment",
                max_length=1000,
            ),
        ),
    ]
