# Generated by Django 5.2.8 on 2025-12-01 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0008_alter_story_thumbnail_url'),
        ('payments', '0006_historicalpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.user')),
            ],
            options={
                'verbose_name': 'Story Credit',
                'verbose_name_plural': 'Story Credits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryCreditPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('story_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instagram.storycredit')),
            ],
            options={
                'verbose_name': 'Story Credit Payment',
                'verbose_name_plural': 'Story Credit Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
