# Generated by Django 5.2.8 on 2025-12-01 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0009_storycredit_storycreditpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycredit',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instagram.user'),
        ),
    ]
