# Generated by Django 5.2.8 on 2025-12-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0011_historicalstorycredit'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='blur_data_url',
            field=models.TextField(blank=True),
        ),
    ]
