# Generated by Django 5.2.9 on 2025-12-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instagram", "0012_story_blur_data_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluser",
            name="blur_data_url",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="blur_data_url",
            field=models.TextField(blank=True),
        ),
    ]
