# Generated by Django 5.2.9 on 2025-12-15 09:12

import instagram.misc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0013_historicalpost_post_postmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='thumbnail',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=instagram.misc.get_post_media_upload_location),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=2500, null=True),
        ),
    ]
