# Generated by Django 5.2.9 on 2025-12-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_historicalpost_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='thumbnail_url',
            field=models.URLField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_url',
            field=models.URLField(max_length=2500),
        ),
    ]
