# Generated by Django 5.2.9 on 2025-12-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0015_historicalpost_raw_data_post_raw_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='blur_data_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='blur_data_url',
            field=models.TextField(blank=True),
        ),
    ]
