# Generated by Django 5.2.9 on 2025-12-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0016_historicalpost_blur_data_url_post_blur_data_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='variant',
            field=models.CharField(choices=[('normal', 'Normal'), ('carousel', 'Carousel')], default='normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='variant',
            field=models.CharField(choices=[('normal', 'Normal'), ('carousel', 'Carousel')], default='normal', max_length=15),
        ),
    ]
