# Generated by Django 5.2.9 on 2025-12-16 10:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0017_alter_historicalpost_variant_alter_post_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='post_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='post_created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
