# Generated by Django 5.2.9 on 2025-12-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0018_historicalpost_post_created_at_post_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='reference',
            field=models.CharField(default='', max_length=50),
        ),
    ]
