# Generated by Django 5.2.9 on 2025-12-16 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0019_postmedia_reference'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postmedia',
            unique_together={('post', 'reference')},
        ),
    ]
