# Generated by Django 5.2.9 on 2025-12-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0020_alter_postmedia_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpost',
            name='variant',
            field=models.CharField(choices=[('normal', 'Normal'), ('carousel', 'Carousel'), ('video', 'Video')], default='normal', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='variant',
            field=models.CharField(choices=[('normal', 'Normal'), ('carousel', 'Carousel'), ('video', 'Video')], default='normal', max_length=15),
        ),
    ]
