# Generated by Django 5.2.9 on 2025-12-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0021_alter_historicalpost_variant_alter_post_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='blur_data_url',
            field=models.TextField(blank=True),
        ),
    ]
