# Generated by Django 5.2.9 on 2025-12-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0022_postmedia_blur_data_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalpost',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
