# Generated by Django 5.2.9 on 2025-12-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0023_historicalpost_height_historicalpost_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
