# Generated by Django 5.2.9 on 2025-12-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0024_postmedia_height_postmedia_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='thumbnail_insight',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_insight',
            field=models.TextField(blank=True),
        ),
    ]
