# Generated by Django 5.2.9 on 2025-12-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0025_historicalpost_thumbnail_insight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='thumbnail_insight_token_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_insight_token_usage',
            field=models.IntegerField(default=0),
        ),
    ]
