# Generated by Django 5.2.9 on 2025-12-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0026_historicalpost_thumbnail_insight_token_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
