# Generated by Django 5.2.9 on 2025-12-17 12:07

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0028_enable_pgvector'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
