# Generated by Django 5.2.9 on 2025-12-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0029_historicalpost_embedding_post_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='embedding_token_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='embedding_token_usage',
            field=models.IntegerField(default=0),
        ),
    ]
