# Generated by Django 5.2.9 on 2025-12-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0030_historicalpost_embedding_token_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumbnail_insight',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='thumbnail_insight_token_usage',
            field=models.IntegerField(default=0),
        ),
    ]
