# Generated by Django 5.2.9 on 2025-12-22 07:55

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0031_story_thumbnail_insight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='embedding_token_usage',
            field=models.IntegerField(default=0),
        ),
    ]
