# Generated by Django 5.2.9 on 2026-07-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0036_post_remove_thumbnail_insight'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
